import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://samulinukala.github.io/portfolio/');
  await page.getByRole('link', { name: 'About' }).click();
  await page.getByRole('link', { name: 'Gallery' }).click();
  await page.getByRole('link', { name: 'Devlog' }).click();
  await page.getByRole('textbox', { name: 'Search devlogs...' }).click();
  await page.getByRole('textbox', { name: 'Search devlogs...' }).fill('app');
  await page.getByText('Architecture & frontendArchitecture and design improvements🗓️ 28.9.2026I have').click();
  await page.getByRole('link', { name: 'Forum' }).click();
  await page.getByRole('button', { name: 'human trials Explore' }).click();
  await page.getByRole('button', { name: 'human testing stage who knows' }).click();
  await page.getByText('who knows if this works this').click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('eric_example');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('eric_rules_hard');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Chat' }).click();
  await page.getByRole('textbox', { name: 'Go ahead, say something...' }).click();
  await page.getByRole('textbox', { name: 'Go ahead, say something...' }).fill('hi. i am testing');
  await page.getByRole('button', { name: 'Send' }).click();
  await page.getByRole('textbox', { name: 'Go ahead, say something...' }).click();
  await page.getByRole('textbox', { name: 'Go ahead, say something...' }).fill('cool');
  await page.getByRole('textbox', { name: 'Go ahead, say something...' }).press('Enter');
  await page.getByRole('link', { name: 'Forum' }).click();
  await page.getByRole('button', { name: 'testresults Explore' }).click();
  await page.locator('button:nth-child(18)').click();
  await page.getByRole('button', { name: 'Back to List' }).click();
  await page.getByRole('button', { name: 'Post in this Topic' }).click();
  await page.getByRole('textbox', { name: 'Give your discussion a clear' }).click();
  await page.getByRole('textbox', { name: 'e.g. General, Suggestions,' }).click();
  await page.getByRole('textbox', { name: 'e.g. General, Suggestions,' }).fill('automated testing');
  await page.getByRole('textbox', { name: 'Give your discussion a clear' }).click();
  await page.getByRole('textbox', { name: 'Give your discussion a clear' }).fill('regular test');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).click();
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).fill('this is a playwright srcript');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).fill('this is a playwright script');
  await page.getByRole('textbox', { name: 'What\'s on your mind? Write' }).press('ArrowRight');
  await page.getByRole('button', { name: 'Publish Post' }).click();
  await page.getByRole('button', { name: 'automated testing Explore' }).click();
});